#!/bin/bash
#Description: Instala lo basico en ubuntu 10.10
#		Manejo de bash con uso de interfaz Genome-GTK con zenity, más info:
#		http://library.gnome.org/users/zenity/stable/zenity-message-options.html.es#zenity-error-dialog
#
#
#basado en: "Lo Basico Despues de instalar Ubuntu 10.10"
#		http://www.nierox.com/2010/10/lo-basico-despues-de-instalar-ubuntu-10-10/
#
#

################################################################
#funciones a utilizar ##################################################
########################################################################
function installPack {
		echo "install $1"
		echo "apt-get --force-yes -y build-dep $1"
		apt-get --force-yes -y build-dep $1
		echo "apt-get --force-yes -y install $1"
		apt-get --force-yes -y install $1
}
#--------------
function installGStreamer {
	#echo hola mundo
	pack=faad\
\	gstreamer0.10-ffmpeg\
\	gstreamer0.10-plugins-bad\
\	gstreamer0.10-plugins-bad-multiverse\
\	gstreamer0.10-plugins-ugly\
\	gstreamer0.10-plugins-ugly-multiverse\
\	gstreamer0.10-pitfdll
	installPack $pack
}

#seleción de idioma
langselect=`zenity --title="Seleccione su idioma" --width=370 --height=180 \
                            --text="Select:" \
                            --list --column="Selected" --column="Language" \
                            --radiolist TRUE Spanish FALSE English `

#Cargamos en L18N la idiomaseleccionada apartir de su respectivo archivo
if [ $? -eq 0 ];
then
        IFS="|"
        for langSselect in $langselect
        do
               if [ "$langSselect" = "English" ];
                     then 
                     YOURLANG="languages/en.pot"
               elif [ "$langSselect" = "Spanish" ];
                     then
                     YOURLANG="languages/es.pot"                     
               fi
        done
        IFS=""
else
        echo cancel selected
        exit
fi

LANGFILE=$(cat $YOURLANG)

n=1
while read curline; do
	export I18N$n="$curline" #> /dev/null 2>&1
	let n=n+1
done < $YOURLANG

#Requiere de una conexion a internet para poder continuar, intentamos acceder a google con wget
testconnection=`wget --tries=3 --timeout=15 www.google.com -O /tmp/testinternet &>/dev/null 2>&1`
if [ $? != 0 ];
then
	zenity --error --title="$I18N1"  --text="$I18N3"
else
	zenity --info --title="$I18N1"  --text="$I18N4"
fi

#Detectando si es super usuario
if [ `id -g` -ne 0 ]
then
  zenity --error --title="$I18N1"  --text="$I18N2"
  exit 1
fi


###--------------------------------------------------------------------
choices=`/usr/bin/zenity --title="$I18N1" --width=500 --height=450 \
                          --text="$I18N5" \
                         --list --column="$I18N6" --column="$I18N7" \
                         --checklist TRUE "$I18N8" FALSE "$I18N9" FALSE "$I18N10" FALSE "$I18N11" FALSE "$I18N12" FALSE "$I18N13" FALSE "$I18N14" FALSE "$I18N15" FALSE "$I18N16" FALSE "$I18N17" FALSE "$I18N18" FALSE "$I18N19" `


#Cachando e instalando solo las opciones q el usario haya elegido
#Existen distintas formas de cachado, esta se basa del echo q exista deteminada
#palabra en las opciones ($choices) la cual sera una especie de clave, 
#OjO esta palabras clave tendran q aparecer en todas las idiomas
echo $choices;
echo "--------------------------"

op=`echo $choices | grep -o gStreamer`
if [ $? == 0 ];
then
	#Codecs Multimedia GStreamer
	echo Codecs Multimedia GStreamer
	installGStreamer
fi
op=`echo $choices | grep -o msttcorefonts`
if [ $? == 0 ];
then
	#Codecs Multimedia GStreamer
	installPack msttcorefonts
	fc-cache
fi
#aqui deben de continuar las demas opciones...
#.............

#Aqui deberia de acabar el script
exit 0

################################ opciones todavia no implementada ##############################################
#################################################################################################################

#Efectos Generales Compiz Fusion
sudo apt-get install compizconfig-settings-manager

#Efectos extras para elcompiz
sudo apt-get install compiz-fusion-plugins-extra

#Emesene [ mensajería instantánea ]
apt-get install emesene

#Amsn [ mensajería instantánea ]
apt-get install amsn

#Vlc [ Reproductor de vídeo ]
apt-get install vlc

#Mplayer [ Reproductor de vídeo ]
apt-get install mplayer

#RAR [ Soporte para descomprimir archivos RAR ]
apt-get install rar

#Inkscape [ manipulador de gráficos ]
apt-get install inkscape

#Banshee [ Reproductor de musica ]
apt-get install banshee

#Xchat [ cliente de IRC ]
apt-get install xchat

#GIMP [ edito de imagenes ]
apt-get install gimp

